# Generated by Django 3.2.3 on 2021-07-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Azik_blog', max_length=200),
        ),
    ]
