# Generated by Django 3.2.3 on 2021-07-24 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0007_auto_20210724_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title_tag',
        ),
    ]
