# Generated by Django 3.2.3 on 2021-07-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0009_auto_20210726_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default=' coding ', max_length=200),
        ),
    ]
